Changes

diff --git a/probe-compression/go b/probe-compression/go
--- a/probe-compression/go
+++ b/probe-compression/go
@@ -2,21 +2,23 @@
 
 mvn clean package
 
-export LIMIT=300
+export LIMIT=$1
 
 java -jar target/probe-compression-1.0-SNAPSHOT.jar "$LIMIT"
 
 rm -f "$format.log"
 
-exit
-
-for format in neato twopi circo dot ;
+#for format in neato twopi circo dot ;
+for format in dot ;
 do  
-  echo "Rendering into $format" >> "$format.log"
-  dot war-and-society-1-2-3-4.dot -v -s[96] -Tpng "-K$format" "-owar-and-society-1-2-3-4-limit-$LIMIT-$format.png" 2>&1 | tee -a "$format.log"
-  dot war-and-society-1-2-3-4.dot -v -s[96] -Tsvg "-K$format" "-owar-and-society-1-2-3-4-limit-$LIMIT-$format.svg" 2>&1 | tee -a "$format.log"
-  gzip -k -9 "war-and-society-1-2-3-4-limit-$LIMIT-$format.svg"
-  echo "Done with errorcode=$?" >> "$format.log"
+  #echo "Rendering into PNG $format" | tee -a "$format.log"
+  #dot graphviz/war-and-society-1-2-3-4.dot -v -s[96] -Tpng "-K$format" "-oimages/war-and-society-1-2-3-4-limit-$LIMIT-$format.png" 2>&1 | tee -a "$format.log"
+  #echo "Done with errorcode=$?" | tee -a "$format.log"
+
+  echo "Rendering into SVG $format" | tee -a "$format.log"
+  dot graphviz/war-and-society-1-2-3-4.dot -v -s[96] -Tsvg "-K$format" "-oimages/war-and-society-1-2-3-4-limit-$LIMIT-$format.svg" 2>&1 | tee -a "$format.log"
+  echo "Done with errorcode=$?" | tee -a "$format.log"
+  
+  gzip -f -k -9 "images/war-and-society-1-2-3-4-limit-$LIMIT-$format.svg"
 done;
 
-head 
